[TH2-1284][TH2-1397] Add classes for management metrics. Add ability for resubscribe on canceled subscriber.
th2-net/th2-common-j pull request #104
Opened 2021-08-03 14:51 UTC by Ilya-Loginov-Exactpro

2021-08-04 10:08 UTC, ivandruzhinin requested changes

2021-08-04 10:08 UTC, ivandruzhinin commented on src/main/kotlin/com/exactpro/th2/common/metrics/AbstractMetricArbiter.kt
> +    protected abstract fun metricChangedValue(value: Boolean)
```suggestion
    protected abstract fun onValueChange(value: Boolean)
```

2021-08-04 11:41 UTC, ivandruzhinin requested changes

2021-08-04 11:41 UTC, ivandruzhinin commented on src/main/kotlin/com/exactpro/th2/common/metrics/FileMetricArbiter.kt
> + * Metric arbiter which uses a file to showing its status
```suggestion
 * Metric arbiter which uses a file to show its status
```

2021-08-04 11:41 UTC, ivandruzhinin commented on src/main/kotlin/com/exactpro/th2/common/metrics/MetricArbiter.kt
> +     * Check if monitor is enable
```suggestion
     * Checks if status of a provided [monitor] is `enabled`
```

2021-08-04 11:41 UTC, ivandruzhinin commented on src/main/kotlin/com/exactpro/th2/common/metrics/MetricArbiter.kt
> +     * Enable monitor
```suggestion
     * Changes status of a provided [monitor] to `enabled`
```

2021-08-04 11:41 UTC, ivandruzhinin commented on src/main/kotlin/com/exactpro/th2/common/metrics/MetricArbiter.kt
> +     * Disable monitor
```suggestion
     * Changes status of a provided [monitor] to `disabled`
```

2021-08-04 11:41 UTC, ivandruzhinin commented on src/main/kotlin/com/exactpro/th2/common/metrics/PrometheusMetricArbiter.kt
> + * Metric arbiter which uses a prometheus metric to showing its status
```suggestion
 * Metric arbiter which uses a Prometheus metric to show its status
```

2021-08-04 11:41 UTC, ivandruzhinin commented on src/main/kotlin/com/exactpro/th2/common/metrics/MultiMetricArbiter.kt
> + * Metric arbiter which combining some metric arbiters
```suggestion
 * Metric arbiter which aggregates several other metric arbiters
```

2021-08-04 11:41 UTC, ivandruzhinin commented on src/main/kotlin/com/exactpro/th2/common/metrics/MultiMetricArbiter.kt
>  class MultiMetricArbiter(private val metricsArbiters: List<MetricArbiter>) : MetricArbiter {
Maybe rename to `AggregatingMetricArbiter`?

2021-08-04 11:41 UTC, ivandruzhinin commented on src/main/kotlin/com/exactpro/th2/common/metrics/MetricArbiter.kt
> +     * Register new endpoint
```suggestion
     * Creates new monitor for this metric
```

2021-08-04 11:41 UTC, ivandruzhinin commented on src/main/kotlin/com/exactpro/th2/common/metrics/MetricArbiter.kt
> +     * Status property of the current arbiter.
```suggestion
     * Current metric status.
```

2021-08-04 11:41 UTC, ivandruzhinin commented on src/main/kotlin/com/exactpro/th2/common/metrics/MetricArbiter.kt
> + * Interface for managing logic metrics with multiple monitors which can change metrics value
```suggestion
 * Entity which allows to have multiple monitors for a single metric. 
 * Resulting metric status will be calculated from statuses of all monitors
```

2021-08-04 11:41 UTC, ivandruzhinin commented on src/main/kotlin/com/exactpro/th2/common/metrics/MetricArbiter.kt
>      fun isMonitorEnabled(monitor: MetricMonitor) : Boolean
Maybe rename to `isEnabled`?

2021-08-04 11:41 UTC, ivandruzhinin commented on src/main/kotlin/com/exactpro/th2/common/metrics/MetricMonitor.kt
>       * Enable monitor, that mean all is ok
```suggestion
     * Changes status of this monitor to `enabled`
```

2021-08-04 11:41 UTC, ivandruzhinin commented on src/main/kotlin/com/exactpro/th2/common/metrics/MetricMonitor.kt
>       * Disable monitor, that mean something wrong
```suggestion
     * Changes status of this monitor to `disabled`
```

2021-08-04 11:41 UTC, ivandruzhinin commented on src/main/kotlin/com/exactpro/th2/common/metrics/MetricArbiter.kt
> +    fun register(name: String) : MetricMonitor
Bump

2021-08-04 11:41 UTC, ivandruzhinin commented on src/main/kotlin/com/exactpro/th2/common/metrics/MetricArbiter.kt
> +    fun register(name: String) : MetricMonitor
Also maybe rename to `createMonitor`

2021-08-04 12:56 UTC, ivandruzhinin commented on src/main/kotlin/com/exactpro/th2/common/metrics/MetricArbiter.kt
> +interface MetricArbiter {
Maybe rename to just `Metric`?

2021-08-04 13:32 UTC, Ilya-Loginov-Exactpro commented on src/main/kotlin/com/exactpro/th2/common/metrics/MetricArbiter.kt
> +interface MetricArbiter {
I think we shouldn't change the name because it isn't a metric. It's something to manage a metric.

2021-08-04 13:47 UTC, ivandruzhinin commented on src/main/kotlin/com/exactpro/th2/common/metrics/MetricArbiter.kt
> +interface MetricArbiter {
Maybe, but for me it just looks like a wrapper over a metric with some additional functionality, which can be effectively used as a metric itself

2021-08-05 10:19 UTC, ivandruzhinin requested changes

2021-08-05 10:19 UTC, ivandruzhinin commented on src/main/kotlin/com/exactpro/th2/common/metrics/AggregatingMetric.kt
> + * Metric arbiter which aggregates several other metric arbiters
```suggestion
 * Metric which aggregates several other metrics
```

2021-08-05 10:19 UTC, ivandruzhinin commented on src/main/kotlin/com/exactpro/th2/common/metrics/FileMetric.kt
> + * Metric arbiter which uses a file to show its status
```suggestion
 * Metric which uses a file to show its status
```

2021-08-05 10:19 UTC, ivandruzhinin commented on src/main/kotlin/com/exactpro/th2/common/metrics/Metric.kt
>      fun register(name: String) : MetricMonitor
```suggestion
    fun createMonitor(name: String) : MetricMonitor
```

2021-08-05 10:19 UTC, ivandruzhinin commented on src/main/kotlin/com/exactpro/th2/common/metrics/PrometheusMetric.kt
> + * Metric arbiter which uses a Prometheus metric to show its status
```suggestion
 * Metric which uses a Prometheus metric to show its status
```

2021-08-06 11:28 UTC, ivandruzhinin submitted a review, later dismissed

2021-08-09 10:07 UTC, ivandruzhinin approved these changes

2021-08-09 10:07 UTC, merged