[TH2-1988] Split connection into publishing and consuming
th2-net/th2-common-j pull request #164
Opened 2021-12-08 12:32 UTC by Sergey-Sitnikov-Exactpro

2021-12-08 15:07 UTC, OptimumOpium requested changes
The current problem is that the exception handler and connection recovery handler uses the same atomic counter. So, the triggering will work incorrectly. We should separate the connections for publication and subscription here as well. So, please set common settings for ConnectionFactory and then use specific listeners before creating a connection

2021-12-14 15:02 UTC, andreydrobynin commented on src/main/java/com/exactpro/th2/common/schema/message/impl/rabbitmq/connection/ConnectionManager.java
> +    private final RecoveryListener consumehRecoveryListener = getRecoveryListener(CONSUME_CONNECTION_NAME);
Type in consume**h**RecoveryListener.
And maybe we don't need variables `publishRecoveryListener` and `consumehRecoveryListener` and we can use inline in `.addRecoveryListener()`?

2021-12-14 15:23 UTC, andreydrobynin commented on src/main/java/com/exactpro/th2/common/schema/message/impl/rabbitmq/connection/ConnectionManager.java
> +    private final RecoveryListener consumehRecoveryListener = getRecoveryListener(CONSUME_CONNECTION_NAME);
Type in consume**h**RecoveryListener.
And I think we don't need fields `publishRecoveryListener` and `consumehRecoveryListener` and we can use inline in `addRecoveryListener()`?

2021-12-14 15:23 UTC, andreydrobynin commented on src/main/java/com/exactpro/th2/common/schema/message/impl/rabbitmq/connection/ConnectionManager.java
> +        }
Extract lines 324-336 to method `getHealthMetrics()` like `getRecoveryListener()`?

2021-12-14 15:23 UTC, andreydrobynin commented on src/main/java/com/exactpro/th2/common/schema/message/impl/rabbitmq/connection/ConnectionManager.java
> +        Connection tmpConnection;
Rename to `connection`?

2021-12-14 15:23 UTC, andreydrobynin commented on src/main/java/com/exactpro/th2/common/schema/message/impl/rabbitmq/connection/ConnectionManager.java
> +        case PUBLISH_CONNECTION_NAME:
Format
```
switch (connectionName) {
    case PUBLISH_CONNECTION_NAME:
...
```

2021-12-14 15:23 UTC, andreydrobynin commented on src/main/java/com/exactpro/th2/common/schema/message/impl/rabbitmq/connection/ConnectionManager.java
> +                switch (connectionName) {
I think there are too many `switch (connectionName)`.
Maybe it's better to add `PublishConnectionManager` and `ConsumeConnectionManager` with `ConnectionManager` as parent (or without parent), encaplulate all logic in them and create them in `ConnectionManager` constructor?

2021-12-15 07:45 UTC, andreydrobynin commented on src/main/java/com/exactpro/th2/common/schema/message/impl/rabbitmq/connection/ConnectionManager.java
> +                switch (connectionName) {
Sorry that I confused you, looks like now `PublishConnectionManager` and `ConsumeConnectionManager` are very similar.
I meant that we will not duplicate code in many `switch (connectionName)` and also in these "managers".

2021-12-16 08:42 UTC, andreydrobynin commented on src/main/java/com/exactpro/th2/common/schema/message/impl/rabbitmq/connection/ConnectionManager.java
> +        }
not actual

2021-12-16 08:42 UTC, andreydrobynin commented on src/main/java/com/exactpro/th2/common/schema/message/impl/rabbitmq/connection/ConnectionManager.java
> +        Connection tmpConnection;
not actual

2021-12-16 08:42 UTC, andreydrobynin commented on src/main/java/com/exactpro/th2/common/schema/message/impl/rabbitmq/connection/ConnectionManager.java
> +        case PUBLISH_CONNECTION_NAME:
not actual

2021-12-16 08:42 UTC, andreydrobynin commented on src/main/java/com/exactpro/th2/common/schema/message/impl/rabbitmq/connection/ConnectionManager.java
> +                switch (connectionName) {
not actual

2021-12-16 12:41 UTC, andreydrobynin commented on src/main/java/com/exactpro/th2/common/schema/message/impl/rabbitmq/connection/ConnectionManager.java
>              .build());
done

2021-12-16 13:42 UTC, Nikita-Smirnov-Exactpro approved these changes

2021-12-16 16:23 UTC, merged