[th2-2789] limited attempts for RabbitMQ connection recovery
th2-net/th2-common-j pull request #170
Opened 2021-12-13 17:39 UTC by andreydrobynin

Looks like attempts never were reseted and it was waiting for recovery some big time, please take a look on `recoveryDelay` calculation:
```
int recoveryDelay = connectionManagerConfiguration.getMinConnectionRecoveryTimeout()
        + (connectionManagerConfiguration.getMaxRecoveryAttempts() > 1
        ? (connectionManagerConfiguration.getMaxConnectionRecoveryTimeout() - connectionManagerConfiguration.getMinConnectionRecoveryTimeout())
        / (connectionManagerConfiguration.getMaxRecoveryAttempts() - 1)
        * tmpCountTriesToRecovery
        : 0);
```
`setConnectionRecoveryTriggeringCondition()` called only once when it first time faced with connection problems and `tmpCountTriesToRecovery` always was 0.

2021-12-15 10:00 UTC, Nikita-Smirnov-Exactpro requested changes

2021-12-15 14:22 UTC, andreydrobynin commented on src/main/java/com/exactpro/th2/common/schema/factory/AbstractCommonFactory.java
> +                livenessMonitor
done

2021-12-15 14:22 UTC, andreydrobynin commented on src/main/java/com/exactpro/th2/common/schema/message/impl/rabbitmq/connection/ConnectionManager.java
> +            LOGGER.debug("Set RabbitMQ liveness to true");
done

2021-12-15 14:24 UTC, andreydrobynin commented on src/main/java/com/exactpro/th2/common/schema/message/impl/rabbitmq/connection/ConnectionManager.java
>              metrics.getReadinessMonitor().enable();
I'm not sure about it. As we discussed now we'll have liveness and readiness metrics in `ConnectionManager` and there are some situations when we should enable both metrics: after `ConnectionManager` creation and after recovery.
I think it's more convinient to call both `enable()/disable()` in one row.

2021-12-15 14:26 UTC, andreydrobynin commented on src/main/java/com/exactpro/th2/common/schema/message/impl/rabbitmq/connection/ConnectionManager.java
>                  Thread.sleep(1);
I thought that in this PR I should fix only recovery attempts and nothing more.

2021-12-16 10:02 UTC, Nikita-Smirnov-Exactpro approved these changes

2021-12-16 17:37 UTC, Nikita-Smirnov-Exactpro approved these changes

2021-12-16 18:33 UTC, merged