[Th2 2422] Multiple dictionaries  access methods
th2-net/th2-common-j pull request #182
Opened 2022-01-31 13:10 UTC by Topru333

2022-02-01 10:39 UTC, ivandruzhinin requested changes

2022-02-01 10:39 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/common/schema/factory/CommonFactory.java
> +            if (Files.exists(dictionaryFolder) && Files.isDirectory(dictionaryFolder)) {
Also probably we should check paths only at init

2022-02-01 10:39 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/common/schema/factory/CommonFactory.java
> +            return dictionaries;
```suggestion
            if (!Files.isDirectory(dictionaryFolder)) {
                return Set.of();
            }
            
            try (Stream<Path> files = Files.list(dictionaryFolder)) {
                return files.filter(Files::isRegularFile)
                        .map((dictionary) -> FilenameUtils.removeExtension(dictionary.getFileName().toString()))
                        .collect(Collectors.toSet());
            }
```

2022-02-01 10:39 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/common/schema/factory/CommonFactory.java
> +            if (Files.exists(dictionaryFolder) && Files.isDirectory(dictionaryFolder)) {
```suggestion
            if (Files.isDirectory(dictionaryFolder)) {
```

2022-02-01 10:39 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/common/schema/factory/CommonFactory.java
> +                        if (fileNameWithoutExt.toLowerCase().equals(dictionaryName)) {
```suggestion
                        if (fileNameWithoutExt.equalsIgnoreCase(alias)) {
```

2022-02-01 10:39 UTC, ivandruzhinin commented on src/main/java/com/exactpro/th2/common/schema/factory/CommonFactory.java
> +            Path typeFolder = dictionaryType.resolvePathFrom(getPathToDictionaryTypesDir());
I think this method should also look for dictionary with alias = type for backward compatibility

2022-02-01 10:39 UTC, ivandruzhinin commented on src/test/kotlin/com/exactpro/th2/common/schema/TestDictionaryLoad.kt
> +        }
I don't think that we should mix checking of valid and invalid cases in a single test method

2022-02-01 10:44 UTC, Topru333 commented on src/main/java/com/exactpro/th2/common/schema/dictionary/DictionaryType.java
> +    public Path resolvePathFrom(Path parent) {
Gonna change it back but i could not resist myself from change this
Dictionary.getDictionary(dictionary).resolve(dictionary)

2022-02-01 11:09 UTC, Topru333 commented on src/main/java/com/exactpro/th2/common/schema/factory/CommonFactory.java
>      private final Path oldDictionariesDir;
Yes, we gonna remove it in common 4 but right now we need to support them

2022-02-01 11:17 UTC, Topru333 commented on src/main/java/com/exactpro/th2/common/schema/factory/CommonFactory.java
> +            if (Files.exists(dictionaryFolder) && Files.isDirectory(dictionaryFolder)) {
There no guarantee that default folder exist on init, there cases without dictionary as a result no folder for them

2022-02-03 11:57 UTC, Topru333 commented on src/main/java/com/exactpro/th2/common/schema/factory/AbstractCommonFactory.java
> +     * Read single dictionary
Better to form different defenition

2022-02-03 11:57 UTC, Topru333 commented on src/main/kotlin/com/exactpro/th2/common/schema/factory/FactorySettings.kt
>      var oldDictionariesDir: Path? = null) {
Better to add Deprecatd annotation too

2022-02-03 13:08 UTC, andreydrobynin commented on src/main/java/com/exactpro/th2/common/schema/factory/CommonFactory.java
> +                return files.filter(Files::isRegularFile).map(dictionary -> FilenameUtils.removeExtension(dictionary.getFileName().toString())).collect(Collectors.toSet());
I think it's more readable:
```
return files
        .filter(Files::isRegularFile)
        .map(dictionary -> FilenameUtils.removeExtension(dictionary.getFileName().toString()))
        .collect(Collectors.toSet());
```
What do you think?
I think it's OK if we have short chain like `files.filter(Files::isRegularFile).collect(Collectors.toList())`.

2022-02-03 13:08 UTC, andreydrobynin commented on src/main/java/com/exactpro/th2/common/schema/factory/CommonFactory.java
> + * Default (platform specific) implementation for {@link AbstractCommonFactory}
Why is it needed?

2022-02-03 13:28 UTC, andreydrobynin approved these changes

2022-02-04 08:47 UTC, ivandruzhinin submitted a review, later dismissed

2022-02-04 08:54 UTC, ivandruzhinin approved these changes

2022-02-04 08:58 UTC, merged