Timeout on connection manager close.
th2-net/th2-common-j pull request #251
Opened 2023-02-14 14:10 UTC by isengrims

2023-02-14 14:31 UTC, Nikita-Smirnov-Exactpro commented on gradle.properties
> +release_version=3.45.0
```suggestion
release_version=3.44.1
```

2023-02-14 14:31 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/common/schema/factory/AbstractCommonFactory.java
> +        // FIXME: delete when publish confirms will be used.
```suggestion
        // FIXME: test and migrate to publish confirms approach 
```

2023-02-14 14:37 UTC, Nikita-Smirnov-Exactpro submitted a review, later dismissed

2023-02-16 12:24 UTC, Nikita-Smirnov-Exactpro approved these changes

2023-02-16 12:27 UTC, Nikita-Smirnov-Exactpro requested changes

2023-02-16 12:27 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/common/schema/factory/AbstractCommonFactory.java
> +
Remove this code

2023-02-17 09:39 UTC, Nikita-Smirnov-Exactpro requested changes

2023-02-17 09:39 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/common/schema/message/impl/rabbitmq/connection/ConnectionManager.java
> +                                ChannelHolder channel1 = channelsByPin.get(pinId);
Please add this listener after creating holder and grab it instead of getting each time

2023-02-17 09:39 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/common/schema/message/impl/rabbitmq/connection/ConnectionManager.java
> +                        (deliveryTag, multiple) -> {
Currently common doesn't resend batches, could you please remove messages from cache

2023-02-17 10:28 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/common/schema/message/impl/rabbitmq/connection/ConnectionManager.java
> +                outstandingConfirms.put(sequence, toShortDebugString(MessageGroupBatch.parseFrom(data)));
Also, connection manager must not know about format of message

2023-02-24 15:11 UTC, Nikita-Smirnov-Exactpro submitted a review, later dismissed
Could you please actualize version

2024-06-06 08:04 UTC, OptimumCode commented
Timeout is already added in master branch

2024-06-06 08:04 UTC, closed without merging