TH2-1988-2
th2-net/th2-common-j pull request #321
Opened 2024-07-08 10:21 UTC by lumber1000

2024-07-09 08:05 UTC, Nikita-Smirnov-Exactpro commented on src/main/kotlin/com/exactpro/th2/common/schema/message/impl/context/DefaultMessageRouterContext.kt
>  class DefaultMessageRouterContext(
Please update the end year of copyright here and in other places

2024-07-09 08:05 UTC, Nikita-Smirnov-Exactpro commented on src/test/kotlin/com/exactpro/th2/common/schema/message/impl/rabbitmq/group/IntegrationTestRabbitMessageBatchRouter.kt
> +                    connectionManager,
I think we should use a separate connection manager for testing Routers.

2024-07-10 13:12 UTC, lumber1000 commented on build.gradle
> +    implementation("io.fabric8:kubernetes-client:6.13.1") {
result Kotlin version is 1.8.22

2024-07-10 13:12 UTC, lumber1000 commented on src/main/java/com/exactpro/th2/common/schema/message/MessageRouter.java
>      default void init(@NotNull ConnectionManager connectionManager, @NotNull MessageRouterConfiguration configuration) {
removed

2024-07-10 14:09 UTC, Nikita-Smirnov-Exactpro commented on src/main/kotlin/com/exactpro/th2/common/schema/message/impl/rabbitmq/connection/ConsumeConnectionManager.kt
> +                                        channel.basicReject(deliveryTag, false)
```suggestion
                                        ch.basicReject(deliveryTag, false)
```

2024-07-10 14:09 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/common/schema/message/impl/rabbitmq/connection/ConnectionManager.java
> +        protected final CancelCallback cancelCallback;
```suggestion
        final ManualAckDeliveryCallback deliverCallback;
        final CancelCallback cancelCallback;
```

2024-07-10 14:15 UTC, lumber1000 commented on gradle.properties
> +kapt.include.compile.classpath=true
Because there was the problem with building of project (class not found). This option fixed it. But looks like now I can change it back.

2024-07-11 06:42 UTC, Nikita-Smirnov-Exactpro commented on build.gradle
Please make this change. The plugin 0.1.1 version is already accessed

2024-07-12 05:43 UTC, Nikita-Smirnov-Exactpro requested changes
Could you please investigate the vulnerability and try to fix it by the lib update
commons-compress-1.24.0.jar (pkg:maven/org.apache.commons/commons-compress@1.24.0, cpe:2.3:a:apache:commons_compress:1.24.0:*:*:*:*:*:*:*) : CVE-2024-25710, CVE-2024-26308

2024-07-12 11:41 UTC, Nikita-Smirnov-Exactpro approved these changes

2024-07-12 11:44 UTC, merged

2024-07-14 09:22 UTC, OptimumCode commented on build.gradle
> +// substitute commons-compress:1.24.0 from testcontainers:1.19.8 to version 1.26.2
Just a small note: this comes from **test** dependency. why do we need this substitution for all configurations? They are not present in the production distribution.
Also, we must remember now to remove this block once the **testcontainers** dependency is updated and no longer contains this vulnerability. The best way would be to exclude the test configurations from scanning - we don't get alerts on dependencies that we don't care about and we don't need to do things like this